# Generated by Django 2.0.2 on 2018-03-06 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140)),
                ('title', models.CharField(max_length=100)),
                ('folder_name', models.CharField(default='default', max_length=100)),
                ('image_name', models.CharField(default='default.jpg', max_length=100)),
                ('mode', models.CharField(choices=[('RW', 'Right-Wrong mode'), ('PR', 'Pairs mode')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('RW', 'Right-Wrong mode'), ('PR', 'Pairs mode')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('stats_id', models.AutoField(primary_key=True, serialize=False)),
                ('times_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameDataPairsMode',
            fields=[
                ('gamedata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.GameData')),
                ('pairs', models.CharField(max_length=500)),
            ],
            bases=('games.gamedata',),
        ),
        migrations.CreateModel(
            name='GameDataRightWrongMode',
            fields=[
                ('gamedata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.GameData')),
                ('right_words', models.CharField(max_length=500)),
                ('wrong_words', models.CharField(max_length=500)),
            ],
            bases=('games.gamedata',),
        ),
        migrations.CreateModel(
            name='GameDataStats',
            fields=[
                ('stats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.Stats')),
                ('max_score', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
            ],
            bases=('games.stats',),
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('stats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.Stats')),
                ('jan', models.IntegerField(default=0)),
                ('feb', models.IntegerField(default=0)),
                ('mar', models.IntegerField(default=0)),
                ('apr', models.IntegerField(default=0)),
                ('may', models.IntegerField(default=0)),
                ('jun', models.IntegerField(default=0)),
                ('jul', models.IntegerField(default=0)),
                ('aug', models.IntegerField(default=0)),
                ('sep', models.IntegerField(default=0)),
                ('okt', models.IntegerField(default=0)),
                ('nov', models.IntegerField(default=0)),
                ('dec', models.IntegerField(default=0)),
            ],
            bases=('games.stats',),
        ),
        migrations.AddField(
            model_name='stats',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamedatastats',
            name='game_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameData'),
        ),
    ]
